"""nevers

Revision ID: 06db11cd8556
Revises: df104bc91387
Create Date: 2023-03-28 11:59:13.751714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06db11cd8556'
down_revision = 'df104bc91387'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
