"""nevers

Revision ID: 07082915180a
Revises: efb42c413294
Create Date: 2023-05-04 15:15:41.466413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07082915180a"
down_revision = "efb42c413294"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "community_posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("community_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("user_community")
    op.add_column(
        "communities", sa.Column("open_community", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "communities", sa.Column("avatar", sa.String(length=255), nullable=True)
    )
    op.add_column("communities", sa.Column("verified", sa.Boolean(), nullable=True))
    op.add_column("posts", sa.Column("type", sa.String(length=50), nullable=True))
    op.drop_constraint("posts_owner_id_fkey", "posts", type_="foreignkey")
    op.drop_column("posts", "owner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key("posts_owner_id_fkey", "posts", "user", ["owner_id"], ["id"])
    op.drop_column("posts", "type")
    op.drop_column("communities", "verified")
    op.drop_column("communities", "avatar")
    op.drop_column("communities", "open_community")
    op.create_table(
        "user_community",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("community_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
            name="user_community_community_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_community_user_id_fkey"
        ),
    )
    op.drop_table("community_posts")
    op.drop_table("user_posts")
    # ### end Alembic commands ###
