"""nevers

Revision ID: 3ffbc05d205d
Revises: 7c274e212b72
Create Date: 2023-04-27 12:30:26.191991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3ffbc05d205d"
down_revision = "7c274e212b72"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("personal_chats", "name")
    op.drop_column("personal_chats", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal_chats",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "personal_chats",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
