"""nevers

Revision ID: 4570d05ed5d7
Revises: e9a5566e1278
Create Date: 2023-04-25 12:39:29.925843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4570d05ed5d7"
down_revision = "e9a5566e1278"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_chat",
        sa.Column("sender_id", sa.UUID(), nullable=True),
        sa.Column("receiver_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
    )
    op.create_table(
        "group_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.Column("sender_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personal_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("sender_id", sa.UUID(), nullable=True),
        sa.Column("receiver_id", sa.UUID(), nullable=True),
        op.drop_constraint("messages_user_id_fkey", "messages", type_="foreignkey"),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["personal_chat.receiver_id"],
        ),
        op.create_unique_constraint(
            "uq_personal_chat_receiver_id", "personal_chat", ["receiver_id"]
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("chat_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name="messages_chat_id_fkey"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="messages_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="messages_pkey"),
    )
    op.drop_table("personal_messages")
    op.drop_table("group_messages")
    op.drop_table("personal_chat")
    # ### end Alembic commands ###
