"""nevers

Revision ID: 5b0b21c062b2
Revises: e73c9f78c611
Create Date: 2023-04-27 12:47:32.964451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b0b21c062b2"
down_revision = "e73c9f78c611"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
