"""nevers

Revision ID: 646f36b59a8a
Revises: e27b33fb45ba
Create Date: 2023-05-05 13:04:45.832846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "646f36b59a8a"
down_revision = "e27b33fb45ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_post")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_post",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("post_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name="user_post_post_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_post_user_id_fkey"
        ),
    )
    # ### end Alembic commands ###
