"""nevers

Revision ID: 6fb436ae8cb7
Revises: 33bccaf462d8
Create Date: 2023-03-28 11:42:14.040280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb436ae8cb7'
down_revision = '33bccaf462d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
