"""nevers

Revision ID: b0d9ee17b8bf
Revises: 5d18562fec52
Create Date: 2023-04-06 12:51:20.263797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d9ee17b8bf'
down_revision = '5d18562fec52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
