"""nevers

Revision ID: b81c0e3fb96d
Revises: a28753a97c39
Create Date: 2023-05-05 14:03:22.704793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b81c0e3fb96d"
down_revision = "a28753a97c39"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
