"""nevers

Revision ID: cd29647b43d9
Revises: b81c0e3fb96d
Create Date: 2023-05-05 14:05:11.219025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd29647b43d9"
down_revision = "b81c0e3fb96d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
