"""nevers

Revision ID: d33c88e7dfaf
Revises: 5b0b21c062b2
Create Date: 2023-04-27 12:48:33.223982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d33c88e7dfaf"
down_revision = "5b0b21c062b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
