"""nevers

Revision ID: df104bc91387
Revises: 6fb436ae8cb7
Create Date: 2023-03-28 11:52:37.954756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df104bc91387'
down_revision = '6fb436ae8cb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
