"""nevers

Revision ID: e27b33fb45ba
Revises: 07082915180a
Create Date: 2023-05-05 12:41:56.202954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e27b33fb45ba"
down_revision = "07082915180a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
