"""nevers

Revision ID: e73c9f78c611
Revises: 3ffbc05d205d
Create Date: 2023-04-27 12:44:30.441063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e73c9f78c611"
down_revision = "3ffbc05d205d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
