"""nevers

Revision ID: e9a5566e1278
Revises: b0d9ee17b8bf
Create Date: 2023-04-23 11:39:15.744929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9a5566e1278"
down_revision = "b0d9ee17b8bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_chat_bans",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_chat_bans")
    # ### end Alembic commands ###
