"""nevers

Revision ID: efb42c413294
Revises: d33c88e7dfaf
Create Date: 2023-05-01 13:03:40.710984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "efb42c413294"
down_revision = "d33c88e7dfaf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group_chats", sa.Column("invite_link", sa.String(), nullable=True))
    op.alter_column("group_chats", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, "group_chats", ["invite_link"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group_chats", type_="unique")
    op.alter_column("group_chats", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("group_chats", "invite_link")
    # ### end Alembic commands ###
